steps:
  # Install dependencies
  - name: 'node:20'
    entrypoint: 'corepack'
    args: ['enable', 'pnpm']
    
  - name: 'node:20'
    entrypoint: 'pnpm'
    args: ['install', '--frozen-lockfile']
  
  # Run tests
  - name: 'node:20'
    entrypoint: 'pnpm'
    args: ['test:ci']
    
  # Build applications
  - name: 'node:20'
    entrypoint: 'pnpm'
    args: ['build']
    
  # Build and push backend container
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/civic-mind-api:$COMMIT_SHA', './apps/api']
    
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/civic-mind-api:$COMMIT_SHA']
    
  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'civic-mind-api'
      - '--image=gcr.io/$PROJECT_ID/civic-mind-api:$COMMIT_SHA'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'

  # Deploy frontend to Firebase Hosting
  - name: 'node:20'
    entrypoint: 'npx'
    args: ['firebase', 'deploy', '--only', 'hosting']

substitutions:
  _ENVIRONMENT: 'production'

options:
  machineType: 'E2_HIGHCPU_8'
  substitution_option: 'ALLOW_LOOSE'

timeout: '1200s'
